services:
  sneakers_front:
    container_name: front_react
    build:
      dockerfile: ../Dockerfiles/React/Dockerfile
    command: ["start"]
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true



