services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfiles/app/Dockerfile
      target: development
    command: [ "python"  , "-m", "mvp_sneakers_api" ]
    environment:
      DEBUG: 'True'
      SETTINGS_LOG_FILE: 'True'
      SETTINGS_LOCAL_MODELS_PATH: models
    volumes:
      - "./mvp_sneakers_api:/src/mvp_sneakers_api"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - vmp_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD" ,"nc", "-vz", "-w1", "localhost", "8000" ]
      interval: 5s
      timeout: 20s
      retries: 100
    restart: on-failure

  redis:
    image: redis:latest
    networks:
      - vmp_network
    expose:
      - 6379
    volumes:
      - "redis_data:/bitnami/redis/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: on-failure


  nginx:
    build: Configs/nginx
    restart: always
    networks:
      - vmp_network
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - nginx_logs:/var/log/nginx
    ports:
      - "5010:5010"


volumes:
  redis_data:
    driver: local
  nginx_logs:
    name: nginx_logs

networks:
  vmp_network:
    name: vmp_network
    driver: bridge
